version: 2.1

jobs:
  
  build-medium-amd64:
    machine:
      image: ubuntu-2004:202101-01
   
    working_directory: ~/python-lz4
    steps:
      
      
      - checkout
      - run:
          name: ️️🏗️ pip dev requirements
          command: |
             uname -m 
             sudo apt-get update && sudo apt-get install -y python3.8 && sudo apt-get install -y python3-pip
             sudo apt-get -y install autoconf automake build-essential cmake libtool mercurial pkg-config llvm-dev
             python3.8 -m pip install --upgrade pip
             python3.8 --version
             python3.8 setup.py install
             python3.8 -m pip install meson 
             python3.8 -m pip install pytest ninja 
             export MESON_UNIT_TEST_BACKEND=ninja 
             pip3 install jsonschema
             pip3 install pytest
             ./run_tests.py
             
  build-medium-arm64:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    working_directory: ~/python-lz4
    steps:
      
      - checkout
      - run:
          name: ️️🏗️ pip dev requirements
          command: |
             uname -m 
             sudo apt-get update && sudo apt-get install -y python3.8 && sudo apt-get install -y python3-pip
             sudo apt-get -y install autoconf automake build-essential cmake libtool mercurial pkg-config llvm-dev
             python3.8 -m pip install --upgrade pip
             python3.8 --version
             python3.8 setup.py install
             python3.8 -m pip install meson 
             python3.8 -m pip install pytest ninja 
             export MESON_UNIT_TEST_BACKEND=ninja 
             pip3 install jsonschema
             pip3 install pytest
             ./run_tests.py
workflows:
  version: 2
  python3.8:
    jobs:
      - build-medium-amd64
      - build-medium-arm64
