version: 2.1

jobs:
  
  build-medium-amd64:
    machine:
      image: ubuntu-2004:202101-01
   
    working_directory: ~/python-lz4
    steps:
      
      
      - checkout
      - run:
          name: ️️🏗️ pip dev requirements
          command: |
             uname -m 
             sudo apt-get update && sudo apt-get -y install python3 python3-pip python3-setuptools python3-wheel ninja-build libgtk-3-dev
             pip3 install --upgrade pip
             python3 setup.py install 
             python3 -m pip install meson
             python3 -m pip install pytest ninja 
             pip3 install jsonschema
             export MESON_UNIT_TEST_BACKEND=ninja
             ./run_unittests.py
  build-medium-arm64:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    working_directory: ~/python-lz4
    steps:
      
      - checkout
      - run:
          name: ️️🏗️ pip dev requirements
          command: |
                uname -m
                sudo apt-get update && sudo apt-get -y install python3 python3-pip python3-setuptools python3-wheel ninja-build libgtk-3-dev
                sudo apt-get -y install make
                sudo apt-get -y install autoconf automake build-essential cmake libtool mercurial pkg-config
                sudo apt-get -y install libgmp-dev libmpfr-dev libmpc-dev libgtest-dev libgirepository1.0-dev
                sudo apt-get install libglib2.0-dev -y
                sudo apt-get install llvm-dev -y
                sudo apt-get install libpq-dev -y libxml2-dev -y libxslt1-dev -y python3-dev -y
                sudo apt-get -y install openssl libssl-dev libssl1.0 libgl1-mesa-dev libqt5x11extras5 qtcreator zlib1g-dev liblzma-dev libbz2-dev
                sudo apt-get -y install python-dev libcpputest-dev as31 nasm gfortran valac default-jdk openjdk-8-jdk mono-complete gobject-introspection gtk+-3.0 libboost-all-dev
                sudo apt-get install tachyon -y
                sudo apt-get install cython -y
                sudo apt-get install libatf-c++-2  gcc g++  -y
                sudo apt-get --allow-downgrades install dub mono-complete
                curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --no-modify-path --default-toolchain none --allow-downgrades                   
                python3.8 setup.py install
                python3.8 -m pip install meson
                python3.8 -m pip install pytest ninja
                export MESON_UNIT_TEST_BACKEND=ninja
                ./run_unittests.py
workflows:
  version: 2
  python3.8:
    jobs:
      
      - build-medium-amd64
      - build-medium-arm64
