version: 2.1

orbs:
  python: circleci/python@1.5.0
executors:
  # Your dependencies would go in the docker images that represent
  # the Linux distributions you are supporting
  meson_ubuntu_builder:
    docker:
      - image: your_dockerhub_username/ubuntu-sys
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
jobs:
  manylinux2014-aarch64:
    parameters:
      cibw_build:
        type: string
        default: "cp37-*"
        
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium        
  meson_ubuntu_build:
    executor: meson_ubuntu_builder
    steps:
      - checkout
      - run: meson setup builddir --backend ninja
      - run: meson compile -C builddir
      - run: meson test -C builddir
      - ./run_tests.py
workflows:
  version: 2.1
  linux_workflow:
    jobs:
      - manylinux2014-aarch64:
          matrix:
            parameters:
              cibw_build:
                - "cp37*"    
      - meson_ubuntu_build
