version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  manylinux2014-aarch64:
    parameters:
      cibw_build:
        type: string
        default: "cp37-*"

    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run:
          name: Install dependencies
          command: |
             sudo apt-get update && sudo apt-get -y install python3 python3.8 python3-pip 
             sudo apt-get -y install autoconf automake build-essential cmake libtool mercurial pkg-config
             python3.8 --version
             python3.8 -m pip install --upgrade pip
             python3.8 -m pip install meson 
             python3.8 --version
             python3.8 -m pip install ninja
             pip3 install jsonschema
             sudo apt-get install --reinstall pkg-config cmake-data
             ./run_tests.py
workflows:
  version: 2.1
  main:
    jobs:
      - manylinux2014-aarch64:
          matrix:
            parameters:
              cibw_build:
                - "cp37*"
