version: 2.1

jobs:
  
  build-medium-amd64:
    machine:
      image: ubuntu-2004:202101-01
   
    working_directory: ~/python-lz4
    steps:
      
      
      - checkout
      - run:
          name: ️️🏗️ pip dev requirements
          command: |
             uname -m 
             sudo apt-get update && sudo apt-get -y install python3 python3-pip python3-setuptools python3-wheel ninja-build libgtk-3-dev
             pip3 install --upgrade pip
             python3 setup.py install 
             python3 -m pip install meson
             python3 -m pip install pytest ninja 
             export MESON_UNIT_TEST_BACKEND=ninja
             cd /usr/local/bin
             meson builddir && cd builddir
             meson compile
             meson test
             ./run_unittests.py
  build-medium-arm64:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    working_directory: ~/python-lz4
    steps:
      
      - checkout
      - run:
          name: ️️🏗️ pip dev requirements
          command: |
             uname -m
             sudo apt-get update && sudo apt-get -y install python3 python3-pip python3-setuptools python3-wheel ninja-build libgtk-3-dev
             pip3 install --upgrade pip
             python3 setup.py install 
             python3 -m pip install meson
             python3 -m pip install pytest ninja 
             export MESON_UNIT_TEST_BACKEND=ninja
             ./run_unittests.py
workflows:
  version: 2
  python3.8:
    jobs:
      
      - build-medium-amd64
      - build-medium-arm64
