name: linux

concurrency:
  group: linux-${{ github.head_ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - master
      # Stable branches such as 0.56 or the eventual 1.0
      - '[0-9]+.[0-9]+'
    paths:
      - "mesonbuild/**"
      - "test cases/**"
      - "unittests/**"
      - ".github/workflows/images.yml"
      - ".github/workflows/os_comp.yml"
      - "run_unittests.py"
  pull_request:
    paths:
      - "mesonbuild/**"
      - "test cases/**"
      - "unittests/**"
      - ".github/workflows/images.yml"
      - ".github/workflows/os_comp.yml"
      - "run_unittests.py"

jobs:
  arch:
    name: ${{ matrix.cfg.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cfg:
          - { name: Arch Linux,       id: arch     }
          - { name: Ubuntu Bionic,    id: bionic   }
    container: mesonbuild/${{ matrix.cfg.id }}:latest
    env:
      MESON_CI_JOBNAME: linux-${{ matrix.cfg.id }}-gcc

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      # All environment variables are stored inside the docker image in /ci/env_vars.sh
      # They are defined in the `env` section in each image.json. CI_ARGS should be set
      # via the `args` array ub the image.json
      run: bash -c 'source /ci/env_vars.sh; cd $GITHUB_WORKSPACE; ./tools/run_with_cov.py ./run_tests.py $CI_ARGS'
    - name: Upload coverage report
      run: ./ci/upload_cov.sh "OS Comp [${{ matrix.cfg.name }}]"
        
  armv64_job:
      name: Build and Test for arm64  
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v1
      - name: Set up QEMU
        id: qemu
      - uses: docker/setup-qemu-action@v1
        with:
          python-version: '3.8'
      - name: Install and Run tests
        run: |
            docker run --rm -v ${{ github.workspace }}:/ws:rw --workdir=/ws 
              arm64v8/ubuntu-latest
              bash -exc 'apt-get update && apt-get -y install python3 python3-pip python3-venv curl 
              python3 -m pip install virtualenv && python3 -m venv py38-venv 
              source py38-venv/bin/activate 
              python3 -m pip install meson 
              python3 -m pip install ninja
              ./run_tests.py
              
