name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os:
          - 'ubuntu-20.04'
        python-version:
          - '3.8'
        arch:
          - 'x86_64'
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        
    - name: Install Dependencies
      run: |
        apt-get update && apt-get install python3 && apt install -y python3-pip
        python3 setup.py install 
        python3 -m pip install meson 
        python3 -m pip install pytest ninja 
        export MESON_UNIT_TEST_BACKEND=ninja 
        pip3 install pytest 
        
    - name: test      
      run: |
        pytest
